import { useState } from "react";
import img from "./assets/ai2 copy 10.png";
import flo from "./assets/image.png";

import "./App.css";
// import ImageLoader from "./ImageLoader";
import LazyImage from "./LazyImage";

function App() {
  const [count, setCount] = useState([
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: flo, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
    { src: img, alt: "AI Image" },
  ]);

  return (
    <>
      <div>
        {count.map((item, index) => {
          return (
            <div
              style={{
                width: "50vw",
                height: "50vh",
                overflow: "hidden",
              }}
            >
              <LazyImage
                src={item.src}
                alt="AI Image"
                imageId={"unique-image-id" + index.toString()}
              />
            </div>
          );
        })}
      </div>
      <h1>Vite + React</h1>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  );
}

export default App;
